### ISSUE TITLE
Using opencv

### ISSUE THREAD

**Issue by zhly0** [homm/color-transformations-reconstruction#15]
Hi，homm：
    Thanks for your nice work.This is not a issue，but a question.Can I use opencv instead of  graphicmagic to do the filtering process？
    Thanks.

**Comment by homm** [comment]
There is no color 3D LUT transformations in OpenCV. Though you can use Pillow through [pillow-lut-tools](https://github.com/homm/pillow-lut-tools).

**Comment by zhly0** [comment]
@homm ,Thank you!

**Comment by zhly0** [comment]
Hi，homm：
    When I use the identity image to generate the filtered image，the instagram save the image to jpg instead of png，which means it has information loss，Is there a way to save the image as png in instagram？by the way，I use the identity image generate clarendon filter，it is not exactly the same as your‘s.How is your provided filter generate？

**Comment by homm** [comment]
> Is there a way to save the image as png in instagram

There is no way, as I know. Please, read careful [the Guide](https://github.com/homm/color-filters-reconstruction#guide):

> This file doesn't look like other hald images. This image is specifically designed to oppose distortions which may occur during transformations such as vignetting, scratches, gradients, and JPEG artifacts.

> it is not exactly the same as your‘s

I can't say anything, because I don't know what exactly you are doing and what result you get. What exactly I did and the result you can see in [the Guide](https://github.com/homm/color-filters-reconstruction#guide).
